### ISSUE TITLE
Incorrect git, folders and submit

### ISSUE THREAD

**Issue by LOHankins** [ga-dc/landlord#116]
Somehow, I managed to upload the incorrect version of landlord.  With Andy's help I was able to at least push to this location: https://github.com/LOHankins/landlord/tree/Louis_solution.  If you have any questions, let me know.

**Comment by tylercrosse** [comment]
It looks like you properly forked the exercise, so I'm not sure why you weren't able to make a PR. I forked&cloned the version on your username, made inline comments and then made a PR on your version. Please look at the `files changed` tab on the PR I made to read the feedback.
